version : '3.8'

services:
  db:
    image: 'bitnami/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'agencia-viagens'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  pgadmin:
    image: 'dpage/pgadmin4'
    restart: 'always'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@root.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    ports:
      - '5050:80'

volumes:
  postgresql_data:
    driver: local
